# -*- coding: utf-8 -*-
"""UpperConfidenceBound.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/19Pnovs0_wmP5UoFjsu7P5aHwXKHQ_gWT
"""

# -*- coding: utf-8 -*-
"""
randomSelection.ipynb
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

veriler = pd.read_csv('/content/Ads_CTR_Optimisation.csv')

N = 10000   # how much random numbers you will create
d = 10      # there are ten ads

import math
oduller = [0] * d
tiklamalar = [0] * d
toplam = 0
secilenler = []
for n in range(1, N):
  add = 0
  max_ucb = 0
  for i in range(0, d):
    if tiklamalar[i] > 0:
      ortalama = oduller[i] / tiklamalar[i]
      delta = math.sqrt(3/2 * math.log(n)/tiklamalar[i])
      ucb = ortalama + delta
    else:
      ucb = N*10 
    if max_ucb < ucb:
      max_ucb = ucb
      add = i     
  secilenler.append(add)
  tiklamalar[add] = tiklamalar[add] + 1
  odul = veriler.values[n, add]
  oduller[add] = oduller[add] + odul
  toplam = toplam + odul

toplam

plt.hist(secilenler)
plt.show()

