# -*- coding: utf-8 -*-
"""thompsonsampling.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1dFdhtOvaKOKC0znRMWW-XWA1fBTAzB8c
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

veriler = pd.read_csv('/content/Ads_CTR_Optimisation.csv')

N = 10000   # how much random numbers you will create
d = 10      # there are ten ads

import math
import random

toplam = 0
secilenler = []
sifirlar = [0] * d
birler = [0] * d
for n in range(1, N):
  add = 0
  max_th = 0
  for i in range(0, d):
    rasbeta = random.betavariate(birler[i] + 1, sifirlar[i] + 1)
    if rasbeta > max_th:
      max_th = rasbeta
      add = i
  secilenler.append(add)
  odul = veriler.values[n, add]
  if odul == 1:
    birler[add] = birler[add] + 1
  else:
    sifirlar[add] = sifirlar[add] + 1
  toplam = toplam + odul

print(toplam)

plt.hist(secilenler)
plt.show()

